[phases.setup]
nixPkgsArchive = "ba913eda2df8eb72147259189d55932012df6301"

[phases.build]
cmds = [
    "cd Desktop/web-clone/web-clone && ./mvnw clean install -DskipTests"
]

[start]
cmd = "cd Desktop/web-clone/web-clone && java -jar target/web-clone-0.0.1-SNAPSHOT.jar"
